all:
  children:

    iperf_loopback:
      vars:
        test_type: loopback
        log_subdir: iperf_loopback
      hosts:
        nic-loopback:
          ansible_host: 192.0.2.1        # replace with target host IP
          loopback_pairs:
            - { server_port: eth0, client_port: eth1 }

    rdma_loopback:
      vars:
        test_type: rdma_loopback
        log_subdir: rdma_loopback
        log_subdirs:
          - rdma
          - iface_status
          - pci_logs
      hosts:
        nic-rdma:
          ansible_host: 192.0.2.1        # replace with target host IP
          loopback_pairs:
            - { server_port: eth0, client_port: eth1 }
